modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="realms_middlefantasy"
version="0.1.0-CORE"
displayName="Realms of Middle-Fantasy: Chronicles of Arda"
authors="Simo"
description='''
A vanilla+ mod inspired by Tolkien's Legendarium - CORE Implementation.

Explore dwarven halls, fight orcs, discover elven ruins and forge legendary weapons.
'''
displayURL="https://github.com/simo-br91/realms-middlefantasy"

[[dependencies.realms_middlefantasy]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.realms_middlefantasy]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.realms_middlefantasy]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.2.1,)"
    ordering="AFTER"
    side="BOTH"


